CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number VARCHAR(50) NOT NULL UNIQUE,
  customer_name VARCHAR(200) NOT NULL,
  customer_email VARCHAR(320) NOT NULL,
  customer_phone VARCHAR(50),
  preferred_contact_method VARCHAR(10) NOT NULL CHECK (preferred_contact_method IN ('EMAIL', 'PHONE', 'WHATSAPP')),
  delivery_address_line1 TEXT NOT NULL,
  delivery_address_line2 TEXT,
  delivery_city VARCHAR(150) NOT NULL,
  delivery_region VARCHAR(150),
  delivery_postal_code VARCHAR(30),
  delivery_country_code CHAR(2) NOT NULL CHECK (delivery_country_code ~ '^[A-Z]{2}$'),
  customer_notes TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'AWAITING_PAYMENT', 'PAID', 'IN_PRODUCTION', 'READY', 'SHIPPED', 'DELIVERED', 'REJECTED', 'CANCELLED')),
  pricing_status VARCHAR(10) NOT NULL DEFAULT 'ESTIMATE' CHECK (pricing_status IN ('ESTIMATE', 'FINAL')),
  estimated_subtotal_minor INTEGER NOT NULL DEFAULT 0 CHECK (estimated_subtotal_minor >= 0),
  final_subtotal_minor INTEGER CHECK (final_subtotal_minor IS NULL OR final_subtotal_minor >= 0),
  delivery_fee_minor INTEGER NOT NULL DEFAULT 0 CHECK (delivery_fee_minor >= 0),
  final_total_minor INTEGER CHECK (final_total_minor IS NULL OR final_total_minor >= 0),
  currency CHAR(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  production_started_at TIMESTAMPTZ,
  ready_at TIMESTAMPTZ,
  shipped_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  source_product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  source_variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  product_slug_snapshot VARCHAR(200) NOT NULL,
  variant_name_snapshot VARCHAR(150) NOT NULL,
  variant_sku_snapshot VARCHAR(100) NOT NULL,
  variant_size_snapshot VARCHAR(100),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  estimated_unit_price_minor INTEGER NOT NULL CHECK (estimated_unit_price_minor >= 0),
  final_unit_price_minor INTEGER CHECK (final_unit_price_minor IS NULL OR final_unit_price_minor >= 0),
  customer_request TEXT,
  customer_notes TEXT,
  preview_file_id UUID REFERENCES files(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE order_item_selections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_item_id UUID NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
  source_option_id UUID REFERENCES product_options(id) ON DELETE SET NULL,
  source_option_value_id UUID REFERENCES product_option_values(id) ON DELETE SET NULL,
  option_code_snapshot VARCHAR(100) NOT NULL,
  option_name_snapshot VARCHAR(150) NOT NULL,
  value_code_snapshot VARCHAR(100),
  value_label_snapshot TEXT NOT NULL,
  color_hex_snapshot CHAR(7) CHECK (color_hex_snapshot IS NULL OR color_hex_snapshot ~ '^#[0-9A-Fa-f]{6}$'),
  reference_storage_key_snapshot TEXT,
  price_adjustment_minor_snapshot INTEGER NOT NULL DEFAULT 0,
  affects_3d_snapshot BOOLEAN NOT NULL DEFAULT FALSE,
  three_d_property_snapshot VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (order_item_id, option_code_snapshot)
);
